import { createMergeTarget } from './merge';

/**
 * Creates an object with the same values and keys generated by running each
 * own enumerable string keyed property of object through the callback.
 *
 * @example
 * mapKeys({ a: 1, b: 2 }, (v, k) => k + v) //=> { a1: 1, b2: 2 }
 */
export default function mapKeys<T extends object>(
  obj: T,
  fn: (value: T[keyof T], key: string | symbol) => string | symbol,
): Record<PropertyKey, T[keyof T]> {
  const result: any = createMergeTarget(obj);
  const keys = [
    ...Object.keys(obj),
    ...Object.getOwnPropertySymbols(obj).filter((sym) =>
      Object.prototype.propertyIsEnumerable.call(obj, sym),
    ),
  ] as (string | symbol)[];

  for (const key of keys) {
    const val = obj[key as keyof T];
    const newKey = fn(val, key);
    if (
      typeof newKey === 'string' &&
      (newKey === '__proto__' ||
        newKey === 'constructor' ||
        newKey === 'prototype')
    ) {
      continue;
    }
    result[newKey] = val;
  }

  return result;
}
