/**
 * Creates an object with the same values and keys generated by running each
 * own enumerable string keyed property of object through the callback.
 *
 * @example
 * mapKeys({ a: 1, b: 2 }, (v, k) => k + v) //=> { a1: 1, b2: 2 }
 */
export default function mapKeys<T extends object>(
  obj: T,
  fn: (value: T[keyof T], key: string) => string,
): Record<string, T[keyof T]> {
  const result: any = {};

  for (const key of Object.keys(obj)) {
    const val = obj[key as keyof T];
    const newKey = fn(val, key);
    if (
      newKey === '__proto__' ||
      newKey === 'constructor' ||
      newKey === 'prototype'
    ) {
      continue;
    }
    result[newKey] = val;
  }

  return result;
}
