import { createMergeTarget } from './merge';

/**
 * Creates an object with the same keys and values generated by running each
 * own enumerable string keyed property of object through the callback.
 *
 * @example
 * mapValues({ a: 1, b: 2 }, (v) => v * 2) //=> { a: 2, b: 4 }
 */
export default function mapValues<T extends object, R>(
  obj: T,
  fn: (value: T[keyof T], key: string | symbol) => R,
): Record<keyof T, R> {
  const result: any = createMergeTarget(obj);
  const keys = [
    ...Object.keys(obj),
    ...Object.getOwnPropertySymbols(obj).filter((sym) =>
      Object.prototype.propertyIsEnumerable.call(obj, sym),
    ),
  ] as (string | symbol)[];

  for (const key of keys) {
    result[key as keyof T] = fn(obj[key as keyof T], key);
  }

  return result;
}
