/**
 * Creates an object with the same keys and values generated by running each 
 * own enumerable string keyed property of object through the callback.
 *
 * @example
 * mapValues({ a: 1, b: 2 }, (v) => v * 2) //=> { a: 2, b: 4 }
 */
export default function mapValues<T extends object, R>(
  obj: T,
  fn: (value: T[keyof T], key: string) => R
): Record<keyof T, R> {
  const result: any = {};

  for (const key of Object.keys(obj)) {
    result[key as keyof T] = fn(obj[key as keyof T], key);
  }

  return result;
}
