# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy to Netlify

on:
  push:
    branches: [ main ]
    
  workflow_dispatch:
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14.x'
        cache: 'yarn'
    - run: yarn install
    - run: yarn workspace website build
    - run: yarn netlify deploy --dir website/build --prod --site es-utils.netlify.app
